### PR TITLE
Security issues + i18n refactors

### PR DESCRIPTION
**Pull request by tokland**
### :pushpin: References

-   **Issue:** Closes #?

### CODE REVIEW

**Comment by tokland** [comment]
@p3rcypj Can you please review that the branch is working for you? I've updated some packages to keep the security messages to a minimum. 

I've also enabled linting messages in the "yarn start" console and hidden them in the browser. That's what we are used to in CRA projects and I think it's a sensible configuration.

**Comment by tokland** [comment]
Snyk current status:

``` 
$ snyk test > out; cat out | grep Upgrade; cat out | grep "introduced by" | sed "s/^.*introduced by //" | sort -u
d2@31.10.2 > isomorphic-fetch@2.2.1 > node-fetch@1.7.3 and 1 other path(s)
@dhis2/d2-i18n@1.1.0 > i18next@10.6.0 and 2 other path(s)
@dhis2/d2-i18n-extract@1.0.8 > i18next-scanner@2.11.0 > vinyl-fs@3.0.3 > glob-stream@6.1.0 > glob-parent@3.1.0
@dhis2/d2-i18n-generate@1.2.0 > rimraf@2.7.1 > glob@7.2.3 > inflight@1.0.6 and 1 other path(s)
```

d2 and @dhis2/d2-i18n packages are already in the last version, we'd need upstream to update them.

**Review by p3rcypj — APPROVED** [review]
Everything working as a charm! 🌟

**Comment by tokland** [comment]
- [ ] Improve i18n typings + explicit namespace

**Pull request merged**
